### ISSUE TITLE
Skip certain migrations while running test_model_definitions_match_ddl

### ISSUE THREAD

**Issue by romulorosa** [schireson/pytest-alembic#25]
Hi there,

First of all, thanks for all work here 🏆 

I have a case where I have a migration (generated without --autogenerate option) which creates a table but turns out that I don't have any model mapped to the database (it is a table required by a 3rd party lib), causing the test to fail.
```
Errors:
E   pytest_alembic.plugin.error.AlembicTestFailure: The models decribing the DDL of your database are out of sync with the set of steps described in the revision history. This usually means that someone has made manual changes to the database's DDL, or some model has been changed without also generating a migration to describe that change.
```

I was wondering if there is a way of skipping certain migrations for that particular test.

**Comment by DanCardin** [comment]
Thanks, and thanks for using the plugin!

Practically, I think there's no reasonable way to skip specific migrations, because we're ultimately relying on alembic for the migration tree traversal of migrations.

I think you **do** have a few options though:
1. Alembic has support for [conditional elements](https://alembic.sqlalchemy.org/en/latest/cookbook.html#conditional-migration-elements). Although i could see this being obnoxious to use because of the requirement to use a specific command line flag
2. You could manually conditionally detect an environment variable in your migration (to avoid creating the table) which you set during your tests. This is also somewhat unfortunate.
3. [You could omit that specific table from detection by alembic](https://alembic.sqlalchemy.org/en/latest/autogenerate.html#omitting-table-names-from-the-autogenerate-process).
4. Or you could just define a model for that table.

I'd probably opt for 3 or 4. Ultimately there's no downside to defining a model, that I can see. but if you can't/would prefer not to, seems like explicitly excluding whatever table this is (from detection by --autogenerate, which is what that test is using) by configuring an `include_object` in your `env.py` would be the next most obvious solution.

**Comment by DanCardin** [comment]
Lmk if none of these options are valid options for whatever reason! Closing this issue because i think that they ought to be.
