### ISSUE TITLE
[Question] how can i access data by data-hook?

### ISSUE THREAD

**Issue by whg517** [schireson/pytest-alembic#46]
> The tool is great, but the documentation isn't clear and even confusing.

I now have some data set through alembic Config, but how can I access it in the test case? What do I need to do? I don't see any examples in the documentation.

I found some inspiration with the `pytest_alembic.tests.test_upgrade` code, but it doesn't work in the Asyncio test case.

This is my unit test

> I already configured async according to the [Using Asyncio with Alembic](https://alembic.sqlalchemy.org/en/latest/cookbook.html#using-asyncio-with-alembic)

`conftest.py` :

```python
# ... some code

@pytest.fixture()
def alembic_config():
    return {
        'script_location': str(Path(alembic.__file__).parent),
        "before_revision_data": {
            "fb4d3ab5f38d": [],  # first version, nothing in db
        },
        "at_revision_data": {
            # secondary version, some table in db, and no other version.
            "cc14dfc64697": [
                {"__tablename__": "ip_address",
                 "id": 1,
                 "ip": "127.0.0.1",
                 },
            ]
        },
    }
```

`test_repository.py` :

```python
# ... some code

@pytest.mark.asyncio
async def test_get_all(alembic_runner):
    alembic_runner.migrate_up_to("heads")
    repo = IpAddressRepository()
    res = await repo.get_all()
    assert res

```

An error was reported after running

```text
/home/kevin/.virtualenvs/myproject-B8OT5Rev/bin/python /opt/softwares/jetbrains-apps/apps/PyCharm-P/ch-0/213.5744.248/plugins/python/helpers/pycharm/_jb_pytest_runner.py --path /home/kevin/workspaces/develop/python/crawlerstack/myproject/tests/test_repository.py
Testing started at 下午7:23 ...
Launching pytest with arguments /home/kevin/workspaces/develop/python/crawlerstack/myproject/tests/test_repository.py --no-header --no-summary -q in /home/kevin/workspaces/develop/python/crawlerstack/myproject/tests

============================= test session starts ==============================
collecting ... collected 1 item

test_repository.py::TestBaseRepository::test_get_all 2021-12-28 19:23:16,103 DEBUG asyncio 20350 139815745447744 Using selector: EpollSelector
2021-12-28 19:23:16,103 DEBUG asyncio 20350 139815745447744 Using selector: EpollSelector
FAILED              [100%]
tests/test_repository.py:12 (TestBaseRepository.test_get_all)
self = <tests.test_repository.TestBaseRepository object at 0x7f29603d8c10>
alembic_runner = MigrationContext(command_executor=CommandExecutor(alembic_config=<alembic.config.Config object at 0x7f296037f0d0>, std...ename__': 'ip_address', 'id': 1, 'ip': '127.0.0.1'}]}, minimum_downgrade_revision=None), connection=Engine(sqlite:///))

    @pytest.mark.asyncio
    async def test_get_all(self, alembic_runner):
>       alembic_runner.migrate_up_to("heads")

test_repository.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/kevin/.virtualenvs/myproject-B8OT5Rev/lib/python3.10/site-packages/pytest_alembic/runner.py:120: in migrate_up_to
    return self.managed_upgrade(revision)
/home/kevin/.virtualenvs/myproject-B8OT5Rev/lib/python3.10/site-packages/pytest_alembic/runner.py:100: in managed_upgrade
    current = self.current
/home/kevin/.virtualenvs/myproject-B8OT5Rev/lib/python3.10/site-packages/pytest_alembic/runner.py:70: in current
    current = self.command_executor.run_command("current")
/home/kevin/.virtualenvs/myproject-B8OT5Rev/lib/python3.10/site-packages/pytest_alembic/executor.py:40: in run_command
    executable_command(self.alembic_config, *args, **kwargs)
/home/kevin/.virtualenvs/myproject-B8OT5Rev/lib/python3.10/site-packages/alembic/command.py:543: in current
    script.run_env()
/home/kevin/.virtualenvs/myproject-B8OT5Rev/lib/python3.10/site-packages/alembic/script/base.py:563: in run_env
    util.load_python_file(self.dir, "env.py")
/home/kevin/.virtualenvs/myproject-B8OT5Rev/lib/python3.10/site-packages/alembic/util/pyfiles.py:92: in load_python_file
    module = load_module_py(module_id, path)
/home/kevin/.virtualenvs/myproject-B8OT5Rev/lib/python3.10/site-packages/alembic/util/pyfiles.py:108: in load_module_py
    spec.loader.exec_module(module)  # type: ignore
<frozen importlib._bootstrap_external>:883: in exec_module
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
../src/crawlerstack_proxypool/alembic/env.py:91: in <module>
    asyncio.run(run_migrations_online())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

main = <coroutine object run_migrations_online at 0x7f296023c740>

    def run(main, *, debug=None):
        """Execute the coroutine and return the result.
    
        This function runs the passed coroutine, taking care of
        managing the asyncio event loop and finalizing asynchronous
        generators.
    
        This function cannot be called when another asyncio event loop is
        running in the same thread.
    
        If debug is True, the event loop will be run in debug mode.
    
        This function always creates a new event loop and closes it at the end.
        It should be used as a main entry point for asyncio programs, and should
        ideally only be called once.
    
        Example:
    
            async def main():
                await asyncio.sleep(1)
                print('hello')
    
            asyncio.run(main())
        """
        if events._get_running_loop() is not None:
>           raise RuntimeError(
                "asyncio.run() cannot be called from a running event loop")
E           RuntimeError: asyncio.run() cannot be called from a running event loop

/usr/local/lib/python3.10/asyncio/runners.py:33: RuntimeError










============================== 1 failed in 0.05s ===============================
sys:1: RuntimeWarning: coroutine 'run_migrations_online' was never awaited

Process finished with exit code 1

```

I hope you can give me some ideas, or a small sample code. Thank you.

**Comment by DanCardin** [comment]
The docs (could likely be clearer but also) dont seem to have published! https://github.com/schireson/pytest-alembic/blob/main/docs/source/asyncio.rst is their source.

perhaps following the example in the 2nd section instead of the first section (which appears to have a typo that means it wont work, alternatively see https://github.com/sqlalchemy/alembic/pull/973/files, they haven't yet published a new version of their own docs yet, their live docs example isn't 100% correct

As far as example, I would recommend looking at https://github.com/schireson/pytest-alembic/tree/main/examples/test_async_sqlalchemy_native, as a self-contained asyncio example with `before_revision_data`

Finally, I would say, to make sure you're on the most recent version. I wouldn't expect the most recent releaste to work before the current one, if you're using `before_revision_data`.

Another potential avenue is, what does your `alembic_runner` look like? The default alembic_runner yields a synchronous engine, so you would be required to define your own.

**Comment by whg517** [comment]
Hi, maybe I didn't make it clear.

Data-hooks, as described in the documentation, are automatically inserted into tables during test migrations. So what should MY unit tests to access this data?

My requirement was to be able to load test data before unit tests in the same way [Django loads fixtures](https://docs.djangoproject.com/en/4.0/topics/testing/tools/#fixture-loading) for use in unit tests, unit tests finish cleaning up the data.

**Comment by DanCardin** [comment]
Based on the above stacktrace, your code wasn't making it to the point of data being inserted into your tables. That is absolutely what the data hooks are meant to be doing though, and you should see the resultant rows in the database automatically, since they're being committed.

If you're asking how you get a handle on the database engine, you should likely be defining your own `alembic_engine` fixture, which your test can additionally be dependent on. Or if your code under test is creating its own engine internally, you just need to make sure `alembic_engine` returns an engine which points at the same database your code is.

Just so it's clear, I would scope pytest-alembic tests to tests which are directly related to your migrations and validation of migrations. All tests run through `pytest_runner` are necessarily super slow because they're literally executing your whole migrations history on a real database.

If this is just a question of getting your database tables set up, as defined in your models, with test data, in service is normal-style tests, I would instead recommend, https://pytest-mock-resources.readthedocs.io/en/latest/database.html#rows.

**Comment by DanCardin** [comment]
I'm going to close this, due to the lack of response and because i think my above suggestions ought to work (but feel free to respond if you need more context/examples).

Also docs have been updated relative to one of my previous comments.
