### ISSUE TITLE
Pytest-alembic doesn't understand the type of a mocked resource

### ISSUE THREAD

**Issue by evanaze** [schireson/pytest-alembic#69]
I'm using pytest-alembic in conjunction with `pytest-mock-resources`, and I love the vision, but I'm missing one crucial integration. When I use `create_postgres_fixture`, `pytest-alembic` doesn't get that the database is Postgres and assumes it's SQLite.

In my conftest.py:
```
alembic_engine = create_postgres_fixture(models.Base)
```
In models.py:
```
Base = declarative_base()


class TestResult(Base):
    """Schema for DB"""

    __tablename__ = "test_results"
    test_uuid = Column(Text)
    test_results = Column(JSONB)
```
When I run `pytest-alembic`, `test_upgrade` fails with:
```
AttributeError: 'SQLiteTypeCompiler' object has no attribute 'visit_JSONB'
```

**Comment by DanCardin** [comment]
Unfortunately due to the way alembic works, it's hard to debug this sort of issue without a full reproducible example.

The versions of sqlalchemy/python/pytest-mock-resource/pytest-alembic would be helpful also. And perhaps some minimal env.py. We definitely have some [examples](https://github.com/schireson/pytest-alembic/tree/e4f57c8981fd61e04326acc9592c02e2ee0abff7/examples/test_minimum_downgrade_revision) which work the same way you're attempting to set it up, so it **should** work, unless it's a setup issue or a version issue somewhere.

this `visit_JSONB` portion of the error has me thinking it might be a sqlalchemy version thing and if i can get it reproduced then it should be an easy fix.

**Comment by DanCardin** [comment]
As i mentioned, i think i'll need something closer to one of the [example](https://github.com/schireson/pytest-alembic/tree/main/examples) to be able to reproduce and give better advice.

But another thing came to mind, if you look in the [fixture definitions](https://github.com/schireson/pytest-alembic/blob/main/src/pytest_alembic/plugin/fixtures.py). You could define your own fixture like so:

```python
import pytest_alembic

alembic_engine = create_postgres_fixture(models.Base)

@pytest.fixture
def alembic_runner(alembic_engine):
    config = Config.from_raw_config({}})
    with pytest_alembic.runner(config=config, engine=alembic_engine) as runner:
        yield runner
```

and this would **definitely** pick it up correctly, as far as the fixtures/tests go. Depending on the original issue, you may still need to make adjustments to your `env.py` per the suggestions in the setup guide in the docs.

**Comment by DanCardin** [comment]
Given the lack of response and suggestions of workarounds, i'm going to close this issue. But feel free to comment back and I can reopen it if there are any reproducible examples

**Comment by evanaze** [comment]
Hi @DanCardin. Thanks for the suggestion. How can I use the `alembic_runner` fixture with my tests?

I created a reproducible [example](https://github.com/evanaze/pytest-alembic-sample). Please let me know if you're able to get it to work. FYI I'm using Python 3.8.

**Comment by DanCardin** [comment]
Okay, so it turns out this is due to a somewhat weird behavior/interaction with how pytest produces collection information when you have a flat folder structure (that is `app/` and `tests/` rather than `src/app` and `tests/`).

To address this, 0.10.1 (which should be released by the time i submit this comment) adds a `pytest_alembic_tests_path` option (defaulting to tests/conftest.py), which you can set in your pytest ini/pyproject.toml configuration.

Given your example project, simply upgrading would fix your problem, but if the default `tests/conftest.py` didn't work for your real project, you could set that value to wherever you registered your `alembic_engine` fixture.

Alternatively in any of the current versions of pytest-alembic, you can instead directly import the default tests at any point in your tests directory:

```python
# tests/test_migrations.py
from pytest_alembic.tests import (
    test_model_definitions_match_ddl,
    test_single_head_revision,
    test_up_down_consistency,
    test_upgrade,
)
```

This would then use pytest's native test discovery, and use whatever the nearest `alembic_engine` fixture definition was.

**Comment by evanaze** [comment]
Thanks so much! I appreciate your quick response & fix. Feel free to close at your leisure.
