### ISSUE TITLE
Overriding fixtures doesn't work unless conftest.py is in the root

### ISSUE THREAD

**Issue by devanubis** [schireson/pytest-alembic#70]
Hi, I'm experiencing an issue when running `pytest --test-alembic` where my overridden `alembic_engine` fixture isn't having an effect, unless `conftest.py` is in the project root directory (and not the `src/` sub-directory where all the source and test files are).

I noticed that the automatic alembic tests are triggered against a `tinker.py` script which I have in the root of my project directory, so I tried moving `conftest.py` to the root, and then the tests passed, my `alembic_engine` fixture was used, and everything seemed fine.

So I added an `a.py` to the project root, and the alembic tests then showed as running against _that_ file instead.

Is there something else I need to set to tell pytest_alembic where to run its tests inside `src/` so that the correct config is loaded?

**Comment by DanCardin** [comment]
So it uses the root path of the pytest run to determine where to attach the tests. So for some `pytest tests` invocation, it'd end up attaching inside `tests/` and load from `tests/conftest.py`.

And fwiw, the actual conftest resolution is not handled by pytest-alembic at all, its pure pytest. So I would expect you to see the same fixture resolution behavior for any self-written tests.

Note that if the behavior with the `--test-alembic` flag doesnt work for you, you can always just import the tests directly in some test module:

```python
# tests/foo/bar/test_some_file.py
from pytest_alembic.tests import test_model_definitions_match_ddl, ...
```

This would ensure your tests "register" at whatever location you want in the same way a normally defined test would.

I could perhaps imagine supporting some additional option which lets you customize the path `--test-alembic` to attach to a particular location, but I decided not to do that initially because it was fraught with other issues that made the tests resolution unreliable. But if the above doesn't work for you and If you have a compelling usecase, we can talk about what that might look like.

**Comment by devanubis** [comment]
Ah OK, turns out if I set `testpaths` in my pytest settings to my `src/` directory everything works a treat without polluting the project root.

Thanks for the help!
