### ISSUE TITLE
Bug: during mid-migration check, database has data from latest migration

### ISSUE THREAD

**Issue by Niccolum** [schireson/pytest-alembic#74]
Hello!

On test_upgrade (and other except test_single_head_revision) my 44'th migration fails on unique violation error insert. Looks like on this step all insertions in this table already in db, because if i select data in this migration - i see all data, in different migrations after, include latest, which can be there only after all migrations apply. Maybe, you have thread parallel job, which migrate to head?

UPD: next migrations also failed like create table (which occurs only once in my migrations) . Not only insert issue

Tested on 0.10.0, 0.9.1
python 3.9

**Comment by DanCardin** [comment]
I can't really diagnose this sort of issue without a standalone example (ideally in the style of https://github.com/schireson/pytest-alembic/tree/main/examples), because most issues are highly dependent on the specific set of revisions being run.

Before that, I would encourage you to first start with an empty local database and first verify you can upgrade from that to `head` without issue, to first help verify it's not some issue with the migrations themselves.

**Comment by DanCardin** [comment]
@Niccolum I'm going to close this issue since you never responded with any more context. Feel free to comment back if there's any additional context that would help me help you, and I'd be happy to reopen.

Upon rereading your description, it sounds like your `alembic_engine` fixture may not be set up in a way that resets the database in between tests.
