### ISSUE TITLE
Multiple database support

### ISSUE THREAD

**Issue by ak47** [schireson/pytest-alembic#98]
Hello,

This may be possible, but I'm not sure how to get this working.

In our project, we manage migrations for 2 databases. Within our `alembic` folder we have two folders `db1` and `db2` each with their own `env.py`.

When attempting to run alembic tests, I'm seeing this failure:

```
self = <alembic.config.Config object at 0x1067fbed0>, section = 'alembic', name = 'script_location', default = None

    def get_section_option(
        self, section: str, name: str, default: Optional[str] = None
    ) -> Optional[str]:
        """Return an option from the given section of the .ini file."""
        if not self.file_config.has_section(section):
>           raise util.CommandError(
                "No config file %r found, or file has no "
                "'[%s]' section" % (self.config_file_name, section)
            )
E           alembic.util.exc.CommandError: No config file 'alembic.ini' found, or file has no '[alembic]' section

../../../Library/Caches/pypoetry/virtualenvs/service-YZCmB_cs-py3.11/lib/python3.11/site-packages/alembic/config.py:305: CommandError
```

I'm sure this is probably possible, but I'm not sure what configuration change is needed. 

I haven't found any descriptions of this in documentation or web search.

Any insights is greatly appreciated.

**Comment by DanCardin** [comment]
I think you want to define an [alembic_config](https://pytest-alembic.readthedocs.io/en/latest/api.html#config) fixture that customizes the script_location

```python
from pytest_alembic import Config

@pytest.fixture
def alembic_config():
    return Config(config_options={'script_location': ...})
```
or alternatively config_file_name, depending on how your migrations are organized.

this will probably mean you'll need 1 module/package per database so that the fixtures take effect on the tests you import from the lib (or define yourself). I think with 2 database, you wont be able to utilize the built-in `--test-alembic` running mechanism.

you can, however, import the tests you care about directly `from pytest_alembic.tests import test_upgrade, ...` in a scope that the fixtures you define for each database will apply, if that makes sense. Same file as the fixtures. or the fixtures in a conftest.py and the tests relative to that conftest.

**Comment by mschoettle** [comment]
Thanks for this. I was able to change the example in the documentation (https://pytest-alembic.readthedocs.io/en/latest/running.html#multiple-alembic-histories) to:

```py
history_1 = create_alembic_fixture({'script_location': 'path/to/history_1'})

def test_single_head_revision_history_1(history_1):
    tests.test_single_head_revision(history_1)

...
```

**Comment by DanCardin** [comment]
You above comment seems like there's nothing to do here. Closing. lmk if not!
